---
kind: Service
apiVersion: v1
metadata:
  name: falcon-api
  labels:
    app: falcon-api
spec:
  selector:
    app: falcon-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: 'webport'
